import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/utils/logger.dart';
import '../../shared/domain/entities/context_entity.dart';
import '../../shared/providers/context_providers.dart';

// Context form state for create/edit
class ContextFormState {
  final String title;
  final String type;
  final String description;
  final DateTime? startDate;
  final DateTime? endDate;
  final List<String> assignedReviewerIds;
  final bool isSubmitting;
  final String? error;

  const ContextFormState({
    this.title = '',
    this.type = 'feature',
    this.description = '',
    this.startDate,
    this.endDate,
    this.assignedReviewerIds = const [],
    this.isSubmitting = false,
    this.error,
  });

  ContextFormState copyWith({
    String? title,
    String? type,
    String? description,
    DateTime? startDate,
    DateTime? endDate,
    List<String>? assignedReviewerIds,
    bool? isSubmitting,
    String? error,
  }) {
    return ContextFormState(
      title: title ?? this.title,
      type: type ?? this.type,
      description: description ?? this.description,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      assignedReviewerIds: assignedReviewerIds ?? this.assignedReviewerIds,
      isSubmitting: isSubmitting ?? this.isSubmitting,
      error: error,
    );
  }

  bool get isFormValid =>
      title.isNotEmpty && description.isNotEmpty && type.isNotEmpty;
}

// Context form provider
final contextFormProvider =
    StateNotifierProvider<ContextFormNotifier, ContextFormState>((ref) {
      return ContextFormNotifier();
    });

class ContextFormNotifier extends StateNotifier<ContextFormState> {
  ContextFormNotifier() : super(const ContextFormState());

  void setTitle(String title) {
    state = state.copyWith(title: title);
  }

  void setType(String type) {
    state = state.copyWith(type: type);
  }

  void setDescription(String description) {
    if (description.length <= 500) {
      state = state.copyWith(description: description);
    }
  }

  void setStartDate(DateTime? date) {
    state = state.copyWith(startDate: date);
  }

  void setEndDate(DateTime? date) {
    state = state.copyWith(endDate: date);
  }

  void toggleReviewerAssignment(String userId) {
    final assignees = List<String>.from(state.assignedReviewerIds);
    if (assignees.contains(userId)) {
      assignees.remove(userId);
    } else {
      assignees.add(userId);
    }
    state = state.copyWith(assignedReviewerIds: assignees);
  }

  void reset() {
    state = const ContextFormState();
  }
}

// Create context provider
final createContextProvider =
    FutureProvider.family<void, ({String organizationId, String userId})>((
      ref,
      params,
    ) async {
      final form = ref.watch(contextFormProvider);
      final repository = ref.watch(contextRepositoryProvider);

      if (!form.isFormValid) {
        throw Exception('Form is not valid');
      }

      try {
        final context = Context(
          id: '', // Will be generated by Firestore
          organizationId: params.organizationId,
          ownerId: params.userId,
          title: form.title,
          type: ContextTypeExtension.fromString(form.type),
          description: form.description,
          status: ContextStatus.draft,
          isIdentifiable: true,
          startDate: form.startDate ?? DateTime.now(),
          endDate: form.endDate,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
          assignedReviewerIds: form.assignedReviewerIds,
        );

        final contextId = await repository.createContext(context);
        Logger.info('Context created: $contextId');

        // Assign reviewers if specified
        if (form.assignedReviewerIds.isNotEmpty) {
          // TODO: Implement reviewer assignment logic
        }
      } catch (e) {
        Logger.error('Failed to create context', e);
        rethrow;
      }
    });

// Update context provider
final updateContextProvider =
    FutureProvider.family<void, ({String contextId, String organizationId})>((
      ref,
      params,
    ) async {
      final form = ref.watch(contextFormProvider);
      final repository = ref.watch(contextRepositoryProvider);

      if (!form.isFormValid) {
        throw Exception('Form is not valid');
      }

      try {
        // Fetch current context
        final current = await repository.getContextById(params.contextId);
        if (current == null) {
          throw Exception('Context not found');
        }

        // Update context
        final updated = current.copyWith(
          title: form.title,
          type: ContextTypeExtension.fromString(form.type),
          description: form.description,
          startDate: form.startDate,
          endDate: form.endDate,
          updatedAt: DateTime.now(),
        );

        await repository.updateContext(updated);
        Logger.info('Context updated: ${params.contextId}');
      } catch (e) {
        Logger.error('Failed to update context', e);
        rethrow;
      }
    });

// Activate context (Draft → Active)
final activateContextProvider = FutureProvider.family<void, String>((
  ref,
  contextId,
) async {
  final repository = ref.watch(contextRepositoryProvider);

  try {
    await repository.updateContextStatus(
      contextId: contextId,
      newStatus: ContextStatus.active,
    );
    Logger.info('Context activated: $contextId');
  } catch (e) {
    Logger.error('Failed to activate context', e);
    rethrow;
  }
});

// Pause context
final pauseContextProvider = FutureProvider.family<void, String>((
  ref,
  contextId,
) async {
  final repository = ref.watch(contextRepositoryProvider);

  try {
    await repository.updateContextStatus(
      contextId: contextId,
      newStatus: ContextStatus.paused,
    );
    Logger.info('Context paused: $contextId');
  } catch (e) {
    Logger.error('Failed to pause context', e);
    rethrow;
  }
});

// Close context
final closeContextProvider = FutureProvider.family<void, String>((
  ref,
  contextId,
) async {
  final repository = ref.watch(contextRepositoryProvider);

  try {
    await repository.updateContextStatus(
      contextId: contextId,
      newStatus: ContextStatus.closed,
    );
    Logger.info('Context closed: $contextId');
  } catch (e) {
    Logger.error('Failed to close context', e);
    rethrow;
  }
});

// Get all contexts for organization
final organizationContextsProvider =
    FutureProvider.family<List<Context>, String>((ref, organizationId) async {
      final repository = ref.watch(contextRepositoryProvider);
      return repository.getOrganizationContexts(organizationId);
    });

// Get contexts by status
final contextsByStatusProvider =
    FutureProvider.family<
      List<Context>,
      ({String organizationId, ContextStatus status})
    >((ref, params) async {
      final repository = ref.watch(contextRepositoryProvider);
      final contexts = await repository.getOrganizationContexts(
        params.organizationId,
      );
      return contexts.where((c) => c.status == params.status).toList();
    });

// Get single context
final contextDetailProvider = FutureProvider.family<Context?, String>((
  ref,
  contextId,
) async {
  final repository = ref.watch(contextRepositoryProvider);
  return repository.getContextById(contextId);
});

// Get active contexts only
final activeContextsProvider = FutureProvider.family<List<Context>, String>((
  ref,
  organizationId,
) async {
  final repository = ref.watch(contextRepositoryProvider);
  return repository.getActiveContexts(organizationId);
});
